name: Various file checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.sh'
      - .github/workflows/checks.yaml

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Shellcheck
        run: sudo apt install shellcheck
      - name: Check configure scripts
        run: |
          shellcheck **/*.sh
