name: Escalation workflow container image and manifest push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'escalation/**'
      - 'pipeline/**'
      - 'scripts/**'
      - .github/workflows/escalation.yml
      - .github/workflows/workflow-executor.yml

jobs:
  escalation-workflow:
    uses: ./.github/workflows/workflow-executor.yml
    with:
      workflow_id: escalation
    secrets: inherit

