name: Greeting workflow container image and manifest push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'greeting/**'
      - 'pipeline/**'
      - .github/workflows/greeting.yml
      - .github/workflows/main.yml

jobs:
  call-main-workflow:
    uses: ./.github/workflows/main.yml
    with:
      workflow_id: greeting
    secrets: inherit

