name: Build and push jira-listener container image for Escalation workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'escalation/jira-listener/**'
      - 'pipeline/**'
      - 'scripts/**'
      - .github/workflows/jira-listener.yml
      - .github/workflows/workflow-executor.yml

jobs:
  jira-listener:
    uses: ./.github/workflows/workflow-executor.yml
    with:
      workflow_id: escalation
      application_id: jira-listener
    secrets: inherit