name: Reusable Workflow executing Makefile to execute the CI pipeline for workflows

on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
      application_id:
        required: false
        type: string
        default: 'UNDEFINED'
      push_pr:
        required: false
        type: boolean
        default: true

env:
  DEPLOYMENT_REPO: parodos-dev/serverless-workflows-config
  REGISTRY_REPO: orchestrator
  GH_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Red Hat Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: registry.redhat.io
        username: ${{ secrets.REGISTRY_REDHAT_IO_USER }}
        password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}    
    - name: Build
      run: |
        make WORKFLOW_ID=${{ inputs.workflow_id }} \
          APPLICATION_ID=${{ inputs.application_id }} \
          GIT_TOKEN=${{ env.GH_TOKEN }} \
          REGISTRY_REPO=${{ env.REGISTRY_REPO }} \
          REGISTRY_USERNAME=${{ secrets.NEW_QUAY_USERNAME }} \
          REGISTRY_PASSWORD=${{ secrets.NEW_QUAY_PASSWORD }} \
          build-image push-image
  gen-and-push-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push manifests to CD repo
      run: |
        # TODO: update PR_OR_COMMIT_URL with PR's URL, if it comes from a PR
        if [ "${{ github.event.head_commit.url }}" != "" ]; then
          PR_OR_COMMIT_URL="${{ github.event.head_commit.url }}"
        else
          PR_OR_COMMIT_URL="${GITHUB_SHA::7}"
        fi

        WORKDIR=${{ runner.temp }}/serverless-workflows
        make WORKFLOW_ID=${{ inputs.workflow_id }} \
          WORKDIR=${WORKDIR} \
          APPLICATION_ID=${{ inputs.application_id }} \
          GIT_USER_NAME=${{ github.actor }} \
          GIT_USER_EMAIL="${{ github.actor }}@users.noreply.github.com" \
          GIT_TOKEN=${{ env.GH_TOKEN }} \
          PR_OR_COMMIT_URL=${PR_OR_COMMIT_URL} \
          gen-manifests push-manifests
    - name: Send PR
      run: |
        WORKDIR=${{ runner.temp }}/serverless-workflows
        cd ${WORKDIR}/helm-repo
        # TODO Put these in env variables
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }} "
        git config -l

        # TODO: reuse PR_OR_COMMIT_URL from these 2 jobs
        if [ "${{ github.event.head_commit.url }}" != "" ]; then
          PR_OR_COMMIT_URL="${{ github.event.head_commit.url }}"
        else
          PR_OR_COMMIT_URL="${GITHUB_SHA::7}"
        fi

        gh repo set-default ${{ env.DEPLOYMENT_REPO }}

        # Construct the PR body
        PR_BODY="Updating generated manifests"
        PR_BODY+=" for ${{ inputs.workflow_id }} workflow"
        if [ "${{ inputs.application_id }}" != "" ]; then
          PR_BODY+=" and application ${{ inputs.application_id }}"
        fi
        PR_BODY+="\n\nThis PR was created automatically as a result of merging ${PR_OR_COMMIT_URL}"

        # Create the PR using the constructed body
        gh pr create -f --title "${{ inputs.workflow_id }}: Automatic manifests generation" --body "${PR_BODY}"